apiVersion: v1
kind: Service # Create service
metadata:
  name: imt-backend-apis # Sets the service name
  labels:
    app: imt-backend-apis # Defines app to create service for
spec:
  ports:
    - port: 8080
      name: imt-backend-api
  selector:
    app: imt-backend-apis