apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: logs # Sets PVC's name
  labels:
    app: logs # Defines app to create PVC for
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 21Gi # Sets PVC's size
