apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: imt-dc-models-volume-claim # Sets PVC's name
  labels:
    app: imt-models # Defines app to create PVC for
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi # Sets PVC's size
