apiVersion: v1
kind: Pod
metadata:
  name: imt-domain-training
  labels:
    app: imt-domain-training
spec:
  containers:
    - name: imp-train-domain-models
      image: registry.gitlab.bsc.es/support/intelcomp/ic-interactive-model-trainer-domain-modeling-api:0.0.40
      imagePullPolicy: "IfNotPresent"
#      command: [ "/bin/bash", "-c", "--" ]
#      args: [ "while true; do sleep 30; done;" ]
#      securityContext:
#        allowPrivilegeEscalation: false
#        runAsUser: 0
      volumeMounts:
        - name: imt-mng-dc-models-data
          mountPath: /data/dc-models
        - name: imt-mng-corpus-data
          mountPath: /data/datasets
        - name: imt-mng-wordlist-data
          mountPath: /data/wordlists
  restartPolicy: Never
  volumes:
    - name: imt-mng-wordlist-data
      persistentVolumeClaim:
        claimName: imt-wordlists-volume-claim
    - name: imt-mng-corpus-data
      persistentVolumeClaim:
        claimName: imt-corpus-volume-claim
    - name: imt-mng-dc-models-data
      persistentVolumeClaim:
        claimName: imt-dc-models-volume-claim
  imagePullSecrets:
    - name: bsc-docker-reg-credentials