apiVersion: apps/v1
kind: Deployment
metadata:
  name: imt-mng
  labels:
    app: imt-mng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imt-mng
  template:
    metadata:
      labels:
        app: imt-mng
    spec:
      containers:
        - name: imt-mng-wordlist
          image: registry.gitlab.bsc.es/support/intelcomp/ic-interactive-model-trainer-wordlists-api:0.0.40
          command: ["tail", "-f", "/dev/null" ]
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: imt-mng-wordlist-data
              mountPath: /data/wordlists
            - name: imt-mng-wordlist-data
              mountPath: /data/temp
        - name: imt-mng-corpus
          image: registry.gitlab.bsc.es/support/intelcomp/ic-interactive-model-trainer-corpus-api:0.0.40
          command: ["tail", "-f", "/dev/null" ]
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: imt-mng-corpus-data
              mountPath: /data/datasets
            - name: imt-mng-corpus-data
              mountPath: /data/temp
        - name: imt-mng-models
          image: registry.gitlab.bsc.es/support/intelcomp/ic-interactive-model-trainer-models-api:0.0.40
          command: ["tail", "-f", "/dev/null" ]
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: imt-mng-models-data
              mountPath: /data/TMmodels
            - name: imt-mng-dc-models-data
              mountPath: /data/dc-models
            - name: imt-mng-topic-modeling-data
              mountPath: /data/topic-modeling
      volumes:
        - name: imt-mng-wordlist-data
          persistentVolumeClaim:
            claimName: imt-wordlists-volume-claim
        - name: imt-mng-corpus-data
          persistentVolumeClaim:
            claimName: imt-corpus-volume-claim
        - name: imt-mng-models-data
          persistentVolumeClaim:
            claimName: imt-models-volume-claim
        - name: imt-mng-dc-models-data
          persistentVolumeClaim:
            claimName: imt-dc-models-volume-claim
        - name: imt-mng-topic-modeling-data
          persistentVolumeClaim:
            claimName: imt-topic-modeling-volume-claim
      imagePullSecrets:
        - name: bsc-docker-reg-credentials