apiVersion: v1
kind: Pod
metadata:
  name: imt-resetTM
  labels:
    app: imt-resetTM
spec:
  containers:
    - name: imt-reset-model
      image: registry.gitlab.bsc.es/support/intelcomp/ic-interactive-model-trainer-reset-topic-modeling-api:0.0.40
      imagePullPolicy: "IfNotPresent"
#      command: [ "/bin/bash", "-c", "--" ]
#      args: [ "while true; do sleep 30; done;" ]
#      securityContext:
#        allowPrivilegeEscalation: false
#        runAsUser: 0
      volumeMounts:
        - name: imt-mng-models-data
          mountPath: /data/models
  restartPolicy: Never
  volumes:
    - name: imt-mng-models-data
      persistentVolumeClaim:
        claimName: imt-models-volume-claim
  imagePullSecrets:
    - name: bsc-docker-reg-credentials