apiVersion: apps/v1
kind: Deployment
metadata:
  name: imt-mng
  labels:
    app: imt-mng
spec:
  replicas: 3 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: imt-mng
  template:
    metadata:
      labels:
        app: imt-mng
    spec:
      containers:
        - name: imt-mng-wordlist
          image: mng-lsts # Docker image
          command: ["tail", "-f", "/dev/null" ]
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: imt-mng-wordlist-data
              mountPath: /data/wordlists
            - name: imt-mng-wordlist-temp
              mountPath: /data/temp
        - name: imt-mng-corpus
          image: mng-corpus # Docker image
          command: ["tail", "-f", "/dev/null" ]
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: imt-mng-corpus-data
              mountPath: /data/datasets
            - name: imt-mng-corpus-temp
              mountPath: /data/temp
        - name: imt-mng-models
          image: mng-mdls # Docker image
          command: ["tail", "-f", "/dev/null" ]
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: imt-mng-models-data
              mountPath: /data/models
            - name: imt-mng-models-temp
              mountPath: /data/temp
      volumes:
        - name: imt-mng-wordlist-data
          hostPath:
            path: /run/desktop/mnt/host/c/Users/sgiannopoulos/Desktop/intelcomp/imt/wordlist_docker/wordlists
            type: Directory
        - name: imt-mng-corpus-data
          hostPath:
            path: /run/desktop/mnt/host/c/Users/sgiannopoulos/Desktop/intelcomp/imt/corpus_docker/datasets
            type: Directory
        - name: imt-mng-models-data
          hostPath:
            path: /run/desktop/mnt/host/c/Users/sgiannopoulos/Desktop/intelcomp/imt/models_docker/models
            type: Directory
        - name: imt-mng-wordlist-temp
          hostPath:
            path: /run/desktop/mnt/host/c/Users/sgiannopoulos/Desktop/intelcomp/imt/wordlist_docker/temp
            type: Directory
        - name: imt-mng-corpus-temp
          hostPath:
            path: /run/desktop/mnt/host/c/Users/sgiannopoulos/Desktop/intelcomp/imt/corpus_docker/temp
            type: Directory
        - name: imt-mng-models-temp
          hostPath:
            path: /run/desktop/mnt/host/c/Users/sgiannopoulos/Desktop/intelcomp/imt/models_docker/temp
            type: Directory