apiVersion: v1
kind: Service # Create service
metadata:
  name: imt-proxy # Sets the service name
  labels:
    app: imt-proxy # Defines app to create service for
spec:
  externalIPs:  
    - ΧΧΧΧΧ 
  type: NodePort # Sets the service type
  ports:
    - port: 8080 # Sets the port to run the postgres application
      nodePort: 32707
  selector:
    app: imt-proxy