package gr.cite.intelcomp.interactivemodeltrainer.common.enums;

public enum CommandType {
    WORDLIST_GET, WORDLIST_CREATE, WORDLIST_COPY, WORDLIST_RENAME, WORDLIST_DELETE,
    CORPUS_GET, CORPUS_GET_RAW, CORPUS_GET_LOGICAL, CORPUS_CREATE, CORPUS_COPY, CORPUS_RENAME, CORPUS_DELETE,
    MODEL_GET, MODEL_GET_TOPIC, MODEL_GET_DOMAIN, MODEL_COPY, MODEL_RENAME, MODEL_DELETE, MODEL_RESET,
    TOPIC_GET, TOPIC_LABELS_SET, TOPIC_SIMILAR, TOPIC_FUSE, TOPIC_SORT, TOPIC_DELETE
}
