event-scheduler:
  events:
    run-training:
      parallelTrainingsThreshold: 2
      postponePeriodInSeconds: 60
    check-tasks:
      checkIntervalInSeconds: 20
      cacheOptions:
        validPeriodInSeconds: 60
        taskResponseCacheRetentionInHours: 48
    check-for-imports:
      enabled: true
      checkIntervalInSeconds: 60
      hdfsDataPath: "data/out"
      hdfsServiceUrl: "XXXXX"
      fileSizeThresholdInMB: 20
  task:
    name: EventSchedulerTask
    processor:
      enable: true
      interval-seconds: 10
      options:
        retry-threshold: 300
        max-retry-delay-seconds: 10800
        too-old-to-handle-seconds: 360000
      overrides: [ ]