idpclient:
  claims:
    mapping:
      Subject:
        - type: sub
      Name:
        - type: name
      Client:
        - type: client_id
      AuthenticationMethod:
        - type: amr
      NotBefore:
        - type: nbf
      AuthenticatedAt:
        - type: auth_time
      ExpiresAt:
        - type: exp
      Roles:
        - type: role
      Scope:
        - type: scope
      AccessToken:
        - type: x-access-token
          visibility: SENSITIVE
      Tenant:
        - type: x-tenant
      IssuedAt:
        - type: iat
      Issuer:
        - type: iss
      Audience:
        - type: aud
      TokenType:
        - type: typ
      AuthorizedParty:
        - type: azp
      Authorities:
        - type: authorities
