services:
  services:
    executionsOutputLibrary:
      volumeConfiguration:
        executions_output_folder: ${DOCKER_WORKSPACE}\executions
    manageLists:
      volumeConfiguration:
        wordlists_folder: ${DOCKER_WORKSPACE}\wordlist_docker\wordlists
        temp_folder: ${DOCKER_WORKSPACE}\wordlist_docker\temp
    manageCorpus:
      volumeConfiguration:
        datasets_folder: ${DOCKER_WORKSPACE}\corpus_docker\datasets
        temp_folder: ${DOCKER_WORKSPACE}\corpus_docker\temp
    manageModels:
      volumeConfiguration:
        temp_folder: ${DOCKER_WORKSPACE}\models_docker\temp
    training:
      volumeConfiguration:
        tm_models_folder: ${DOCKER_WORKSPACE}\models_docker\TMmodels
        temp_folder: ${DOCKER_WORKSPACE}\training\temp
    domainTraining:
      volumeConfiguration:
        dc_models_folder: ${DOCKER_WORKSPACE}\models_docker\DCmodels-metadata
        dc_models_inner_folder: /data/DCmodels-metadata
        temp_folder: ${DOCKER_WORKSPACE}\training\temp
        output_folder: ${DOCKER_WORKSPACE}\models_docker\dc-models\{project_name}_classification\output
        documents_folder: ${DOCKER_WORKSPACE}\models_docker\dc-models\{project_name}_classification\datasets\temp
        zero_shot_folder: ${DOCKER_WORKSPACE}\models_docker\DCmodels-zero-shot