services:
  services:
    manageLists:
      volumeConfiguration:
        temp_folder: ${DOCKER_WORKSPACE}\wordlist_docker\temp
    manageCorpus:
      volumeConfiguration:
        temp_folder: ${DOCKER_WORKSPACE}\corpus_docker\temp
    manageModels:
      volumeConfiguration:
        temp_folder: ${DOCKER_WORKSPACE}\models_docker\temp
    training:
      volumeConfiguration:
        models_folder: ${DOCKER_WORKSPACE}\models_docker\models
        temp_folder: ${DOCKER_WORKSPACE}\training\temp