kubernetes:
  kubeConfPath: /management-config/kube-config
  services:
    manageLists:
      deploymentName: management
      containerName: imt-mng-wordlist
    manageCorpus:
      deploymentName: management
      containerName: imt-mng-corpus
    manageModels:
      deploymentName: management
      containerName: imt-mng-models
  jobs:
    trainModels:
      jobName: training
      containerName: imt-train-models
    resetModel:
      jobName: resetTM
      containerName: imt-reset-model
    trainDomainModels:
      jobName: domainTraining
      containerName: imp-train-domain-models
  deployments:
    management:
      path: /management-config/management-deployment.yml
      deploymentLabelSelector: app=imt-mng
      podLabelSelector: app=imt-mng
  pods:
    training:
      path: /management-config/topic-modeling-pod.yml
      podLabelSelector: app=imt-train
    resetTM:
      path: /management-config/reset-topic-modeling-pod.yml
      podLabelSelector: app=imt-resetTM
    domainTraining:
      path: /management-config/domain-training-pod.yml
      podLabelSelector: app=imt-domain-training