apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: imt-frontend # Set the name of the deployment
spec:
  replicas: 1 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: imt-frontend
  template:
    metadata:
      labels:
        app: imt-frontend
    spec:
      containers:
        - name: imt-frontend
          image: registry.gitlab.bsc.es/support/intelcomp/ic-interactive-model-trainer-webapp:0.0.42
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          env:
            - name: WEBAPP_BASE_URL
              value: "/"
          volumeMounts:
            - name: "imt-frontend-config"
              mountPath: "/usr/share/nginx/html/assets/config.json"
              subPath: "config.json"
            - name: "imt-frontend-config"
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "nginx.conf"
      volumes:
        - name: imt-frontend-config
          configMap:
            name: imt-frontend
      imagePullSecrets:
        - name: bsc-docker-reg-credentials